### ISSUE TITLE
This is really cool!

### ISSUE THREAD

**Issue by marcospgp** [onury/json-more#1]
Why isn't it more popular? I can't find any alternatives!

Feel free to delete this issue, I'll do it myself soon. I just wanted to show my appreciation with more than a simple star 😄

**Comment by onury** [comment]
:blush: This is the best first-issue I've ever received on my repos.
Definitely means more than a star!

It's just a compilation of separate utilities and some additions. I got tired of including multiple json-related modules in every project..

Thanks a lot.
Cheers
